### ISSUE TITLE
Documentation not in repostiory

### ISSUE THREAD

**Issue by dewhattens** [openpreserve/odf-validator#146]
The documentation lies between this rep and http://odf.openpreservation.org/ and another repo with a specification.

In the case that OPF becomes inactive then we will not have access to http://odf.openpreservation.org/ and hence it is required that all documentation is placed in this repository. This include the definition of the policies which is found in another repo.

**Comment by carlwilson** [comment]
The documentation site is built using the repository content below the docs folder: <https://github.com/openpreserve/odf-validator/tree/main/docs>.

**Comment by dewhattens** [comment]
Major problem is that I cannot find any definition of POL_1 , POL_2 etc on github.
