### ISSUE TITLE
No compression validation for META-INF/manifest.xml

### ISSUE THREAD

**Issue by maria-messerschmidt** [openpreserve/odf-validator#165]
All files listed in the manifest are checked for compression and must be stored or deflated (PKG-2) But files not listed in the manifest (such as the manifest itself) are not validated for compression. 

Example file:
[AT039.ods](https://github.com/user-attachments/files/16345406/AT039.ods)

This file generates the following log the validator (CLI):
C:\odf\odf-validator-main>odf-validator.bat -p "C:\Users\maria\Desktop\2024-07\AT039\AT039.ods"
APP-1: [INFO] Validating C:\Users\maria\Desktop\2024-07\AT039\AT039.ods.
APP-5: [INFO] DNA ODF Spreadsheets Preservation Specification Profile report for C:\Users\maria\Desktop\2024-07\AT039\AT039.ods.
DOC-3: mimetype [INFO] OpenDocument MIMETYPE application/vnd.oasis.opendocument.spreadsheet detected
POL_5: content.xml [INFO] External data check | Table formula detected.
VALID, no errors, no warnings and 2 info message found.

C:\odf\odf-validator-main>odf-validator.bat "C:\Users\maria\Desktop\2024-07\AT039\AT039.ods"
APP-1: [INFO] Validating C:\Users\maria\Desktop\2024-07\AT039\AT039.ods.
APP-4: [INFO] Validation report for C:\Users\maria\Desktop\2024-07\AT039\AT039.ods.
DOC-3: mimetype [INFO] OpenDocument MIMETYPE application/vnd.oasis.opendocument.spreadsheet detected
VALID, no errors, no warnings and 1 info message found.

I validated using odfvalidator.org as well, and here it fails:

The document is NOT conformant ODF1.3!

Details:
AT039.ods: Info: ODF version of root document: 1.3
AT039.ods[-1,-1]: Error: The compression method of the ZIP entry 'META-INF/manifest.xml' is not allowed within the 'AT039.ods' ODF package file!
internal:/schema/odf1.3/OpenDocument-v1.3-manifest-schema.rng: Info: parsed.
AT039.ods/META-INF/manifest.xml: Info: no errors, no warnings
AT039.ods/mimetype: Info: no errors, no warnings
AT039.ods: Info: Media Type: application/vnd.oasis.opendocument.spreadsheet
internal:/schema/odf1.3/OpenDocument-v1.3-schema.rng: Info: parsed.
AT039.ods/meta.xml: Info: Generator: LibreOffice/24.2.0.3$Windows_X86_64 LibreOffice_project/da48488a73ddd66ea24cf16bbc4f7b9c08e9bea1
AT039.ods/meta.xml: Info: no errors, no warnings
AT039.ods/settings.xml: Info: no errors, no warnings
AT039.ods/styles.xml: Info: no errors, no warnings
AT039.ods/content.xml: Info: no errors, no warnings
internal:/schema/odf1.3/OpenDocument-v1.3-dsig-schema.rng: Info: parsed.
AT039.ods: Info: 1 errors, no warnings

**Comment by maria-messerschmidt** [comment]
This works now and can be closed. See log below:

C:\odf\odf-validator-main>odf-validator.bat -p "C:\Users\maria\Desktop\2024-07\AT039\AT039.ods"
APP-1: [INFO] Validating C:\Users\maria\Desktop\2024-07\AT039\AT039.ods.
APP-5: [INFO] DNA ODF Spreadsheets Preservation Specification Profile report for C:\Users\maria\Desktop\2024-07\AT039\AT039.ods.
DOC-2: [INFO] package OpenDocument version 1.3 detected.
DOC-3: [INFO] mimetype OpenDocument MIMETYPE application/vnd.oasis.opendocument.spreadsheet detected
PKG-2: [ERROR] META-INF\manifest.xml All files contained in the Zip file shall be non compressed (STORED) or compressed using the "deflate" (DEFLATED) algorithm. **Zip entry META-INF/manifest.xml is compressed with an unknown algorithm.**
POL_2: [ERROR] AT039.ods Standard Compliance | Package does not comply with specification. The file MUST comply with the standard "OASIS Open Document Format for Office Applications (OpenDocument) v1.3".
NOT VALID, 2 errors, 0 warnings and 2 info messages.

**Comment by carlwilson** [comment]
Good to have this confirmed.
