### ISSUE TITLE
Support delimiting validation of extension

### ISSUE THREAD

**Issue by Asbjoedt** [openpreserve/odf-validator#17]
See this issue https://github.com/opf-labs/sheets-preservation-spec/issues/8 for context.

The validator should support a config/policy file so any organisation may validate only a subset of file format extensions. How to implement the config/policy file must be documented, so it is easy for an organisation to use this option.

**Comment by carlwilson** [comment]
Do you mean to filter by extension only OR the underlying real MIME type. Remember that if the two are inconsistent, it will be a validation error. An extension is a dubious element to chose for this.

**Comment by Asbjoedt** [comment]
ODS_2 is standard compliance and the standard defines pairs of extension and MIME types, so the check would fail here if the two are not consistent?

ODS_3 is then only the extension, because in ODS_2 we already validated the correct MIME type associated with the extension.

You get what I mean?

**Comment by carlwilson** [comment]
Closed by #104
