### ISSUE TITLE
Change in ordering of the error message details

### ISSUE THREAD

**Issue by maria-messerschmidt** [openpreserve/odf-validator#172]
In version 0.10 error messages were shown in this order (message key,  file/zip entry, [SEVERITY], error message):

POL_4: mimetype [ERROR] Extension and MIME type | The MIME type value MUST be: "application/vnd.oasis.opendocument.spreadsheet" and the file extension MUST be ".ods".

Now, in 0.12, they are shown in a different order (message key, [SEVERITY],  file/zip entry,  error message): 

POL_4: [ERROR] mimetype Extension and MIME type | The MIME type value MUST be: "application/vnd.oasis.opendocument.spreadsheet" and the file extension MUST be ".ods".

This does seem more consistent with the APP-x messages which were always this way around, but is it deliberate? And if this is the order as it should be, could we make sure we don't change it again? :)

**Comment by carlwilson** [comment]
The change was deliberate for consistency. I'm not intending to change again and would only do so in response to issues generally.
