### ISSUE TITLE
Support validation of embedded files

### ISSUE THREAD

**Issue by Asbjoedt** [openpreserve/odf-validator#18]
Hi!

We need a way to process embedded files for validation in our existing/other validation workflows e.g. if an image is embedded, the image should be validated according to our organisation's image file format policies.

The validator should therefore allow for a method, possibly returning a list of embedded files with their paths, when validating the ODS_5 requirement.

**Comment by carlwilson** [comment]
The package parser allows access to the streams of all entries with some convenience methods for access embedded files.
