### ISSUE TITLE
ODS-10 not dettected

### ISSUE THREAD

**Issue by dewhattens** [openpreserve/odf-validator#55]
File with settings does not return ODS-10

Testing D:\ODS1\TestCorpusV2\ODS-10\WithSettings.ods
APP-1: [INFO] Validating D:\ODS1\TestCorpusV2\ODS-10\WithSettings.ods.
APP-4: [INFO] Validation report for D:\ODS1\TestCorpusV2\ODS-10\WithSettings.ods.
DOC-3: mimetype [INFO] OpenDocument MIMETYPE application/vnd.oasis.opendocument.spreadsheet detected
VALID, no errors, no warnings and 1 info message found.

**Comment by carlwilson** [comment]
ODS_10 is now sub-document detection, will close this and open a new issue.
